/**
 * Supabase database types.
 *
 * This file is normally generated by `npm run db:types` once the project is
 * linked (`supabase link`). Until then it is hand-maintained to match the
 * migrations in supabase/migrations/ — keep the two in sync.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

type Timestamps = {
  created_at: string;
  updated_at: string;
};

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string | null;
          full_name: string | null;
          avatar_url: string | null;
        } & Timestamps;
        Insert: {
          id: string;
          email?: string | null;
          full_name?: string | null;
          avatar_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string | null;
          full_name?: string | null;
          avatar_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      ob_connections: {
        Row: {
          id: string;
          user_id: string;
          provider_connection_id: string;
          institution_name: string | null;
          status: "active" | "expired" | "revoked";
          last_synced_at: string | null;
        } & Timestamps;
        Insert: {
          id?: string;
          user_id: string;
          provider_connection_id: string;
          institution_name?: string | null;
          status?: "active" | "expired" | "revoked";
          last_synced_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          provider_connection_id?: string;
          institution_name?: string | null;
          status?: "active" | "expired" | "revoked";
          last_synced_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      ob_tokens: {
        Row: {
          id: string;
          user_id: string;
          connection_id: string | null;
          provider: string;
          access_token: string;
          refresh_token: string;
          expires_at: string;
        } & Timestamps;
        Insert: {
          id?: string;
          user_id: string;
          connection_id?: string | null;
          provider?: string;
          access_token: string;
          refresh_token: string;
          expires_at: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          connection_id?: string | null;
          provider?: string;
          access_token?: string;
          refresh_token?: string;
          expires_at?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "ob_tokens_connection_id_fkey";
            columns: ["connection_id"];
            referencedRelation: "ob_connections";
            referencedColumns: ["id"];
          },
        ];
      };
      ob_accounts: {
        Row: {
          id: string;
          user_id: string;
          connection_id: string;
          provider_account_id: string;
          display_name: string | null;
          account_type: string | null;
          currency: string | null;
          current_balance: number | null;
          available_balance: number | null;
        } & Timestamps;
        Insert: {
          id?: string;
          user_id: string;
          connection_id: string;
          provider_account_id: string;
          display_name?: string | null;
          account_type?: string | null;
          currency?: string | null;
          current_balance?: number | null;
          available_balance?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          connection_id?: string;
          provider_account_id?: string;
          display_name?: string | null;
          account_type?: string | null;
          currency?: string | null;
          current_balance?: number | null;
          available_balance?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "ob_accounts_connection_id_fkey";
            columns: ["connection_id"];
            referencedRelation: "ob_connections";
            referencedColumns: ["id"];
          },
        ];
      };
      ob_transactions: {
        Row: {
          id: string;
          user_id: string;
          account_id: string;
          provider_transaction_id: string;
          amount: number;
          currency: string | null;
          description: string | null;
          merchant_name: string | null;
          category: string | null;
          transaction_type: string | null;
          timestamp: string;
        } & Timestamps;
        Insert: {
          id?: string;
          user_id: string;
          account_id: string;
          provider_transaction_id: string;
          amount: number;
          currency?: string | null;
          description?: string | null;
          merchant_name?: string | null;
          category?: string | null;
          transaction_type?: string | null;
          timestamp: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          account_id?: string;
          provider_transaction_id?: string;
          amount?: number;
          currency?: string | null;
          description?: string | null;
          merchant_name?: string | null;
          category?: string | null;
          transaction_type?: string | null;
          timestamp?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "ob_transactions_account_id_fkey";
            columns: ["account_id"];
            referencedRelation: "ob_accounts";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Views: Record<never, never>;
    Functions: Record<never, never>;
    Enums: Record<never, never>;
    CompositeTypes: Record<never, never>;
  };
};

/* Convenience row aliases ------------------------------------------------- */

type PublicSchema = Database["public"];

export type Tables<T extends keyof PublicSchema["Tables"]> =
  PublicSchema["Tables"][T]["Row"];
export type TablesInsert<T extends keyof PublicSchema["Tables"]> =
  PublicSchema["Tables"][T]["Insert"];
export type TablesUpdate<T extends keyof PublicSchema["Tables"]> =
  PublicSchema["Tables"][T]["Update"];

export type Profile = Tables<"profiles">;
export type ObConnection = Tables<"ob_connections">;
export type ObToken = Tables<"ob_tokens">;
export type ObAccount = Tables<"ob_accounts">;
export type ObTransaction = Tables<"ob_transactions">;
